### ISSUE TITLE
Compiling the example basic player doesn't work

### ISSUE THREAD

**Issue by punchagan** [micmarsh/re-frame-youtube-fx#1]
```js
Uncaught TypeError: YT.Je is not a constructor
    at Yy (app.js:643)
    at app.js:613
    at app.js:263
    at app.js:263
    at hf (app.js:205)
    at gf.k.$ (app.js:208)
    at q (app.js:130)
    at ki (app.js:409)
    at app.js:613
    at Fx (app.js:599)
```

**Comment by punchagan** [comment]
Adding `cljsjs/youtube` as a dependency so that externs for the youtube iframe library are available should fix this.

**Comment by micmarsh** [comment]
Awesome, thanks, sorry for taking so long to reply, it's been a very long time since I've looked at any of this. I'll get on that as soon as I can.

**Comment by punchagan** [comment]
No worries, thanks.

**Comment by micmarsh** [comment]
Should be fixed, pushed directly to master. Let me know how it shakes out for you and I can close the issue.

**Comment by punchagan** [comment]
This seems to be fixed, now. Thanks!
